name: New Feature Check

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - staging
      - master

jobs:
  test:
    runs-on: ubuntu-latest
     # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Flyway
        run: |
          curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/11.1.0/flyway-commandline-8.5.11-linux-x64.tar.gz | tar xz
          sudo ln -s $(pwd)/flyway-11.1.0/flyway /usr/local/bin/flyway

      - name: Run flyway checks
        env:
          FLYWAY_URL: jdbc:postgresql://localhost:5432/postgres
          FLYWAY_USER: postgres
          FLYWAY_PASSWORD: postgres
          FLYWAY_VALIDATE_MIGRATION_NAMING: true
        run: flyway validate

