name: Feature Check

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - staging
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Flyway
        run: |
          curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.5.11/flyway-commandline-8.5.11-linux-x64.tar.gz | tar xz
          sudo ln -s $(pwd)/flyway-8.5.11/flyway /usr/local/bin/flyway

      - name: Run Flyway migrations
        env:
          FLYWAY_URL: jdbc:postgresql://localhost:5432/postgres
          FLYWAY_USER: postgres
          FLYWAY_PASSWORD: postgres
          FLYWAY_VALIDATE_MIGRATION_NAMING: true
        run: flyway migrate

      - name: Testing placeholder
        run: echo 'Testing'
